Bravo/Bravo/Controllers/GeraeteartverwaltungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bravo.Controllers
{
    public class GeraeteartverwaltungController : Controller
    {
        // GET: Geraeteart
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GeraeteartHinzufuegen()
        {
            return View();
        }

        public ActionResult GeraeteartDetails()
        {
            return View();
        }
    }
}

Bravo/Bravo/Controllers/GeraeteverwaltungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bravo.Controllers
{
    public class GeraeteverwaltungController : Controller
    {
        // GET: Geraeteverwaltung
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GeraetHinzufuegen()
        {
            return View();
        }

        public ActionResult GeraetDetails()
        {
            return View();
        }
    }
}

Bravo/Bravo/Controllers/GeraetkomponentenverwaltungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bravo.Controllers
{
    public class GeraetkomponentenverwaltungController : Controller
    {
        // GET: Komponentenverwaltung
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GeraetkomponenteHinzufuegen()
        {
            return View();
        }

        public ActionResult GeraetkomponenteDetails()
        {
            return View();
        }
    }
}

Bravo/Bravo/Views/Geraetkomponentenverwaltung/GeraetkomponenteDetails.cshtml
@{
    ViewBag.Title = "KomponenteDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Geräte", "Index", "Geraeteverwaltung")</li>
            <li>@Html.ActionLink("Gerät hinzufügen", "GeraetHinzufuegen", "Geraeteverwaltung")</li>
            <li>@Html.ActionLink("Übersicht Komponenten", "Index", "Geraetkomponentenverwaltung")</li>
            <li>@Html.ActionLink("Komponente hinzufügen", "GeraetkomponenteHinzufuegen", "Geraetkomponentenverwaltung")</li>
            <li>@Html.ActionLink("Übersicht Gerätearten", "Index", "Geraeteartverwaltung")</li>
            <li>@Html.ActionLink("Geräteart hinzufügen", "GeraeteartHinzufuegen", "Geraeteartverwaltung")</li>
        </ul>
    </div>
</div>


<h3>Komponente bearbeiten</h3>

Bravo/Bravo/Views/Geraetkomponentenverwaltung/GeraetkomponenteHinzufuegen.cshtml
@{
    ViewBag.Title = "KomponenteHinzufuegen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Geräte", "Index", "Geraeteverwaltung")</li>
            <li>@Html.ActionLink("Gerät hinzufügen", "GeraetHinzufuegen", "Geraeteverwaltung")</li>
            <li>@Html.ActionLink("Übersicht Komponenten", "Index", "Geraetkomponentenverwaltung")</li>
            <li>@Html.ActionLink("Komponente hinzufügen", "GeraetkomponenteHinzufuegen", "Geraetkomponentenverwaltung")</li>
            <li>@Html.ActionLink("Übersicht Gerätearten", "Index", "Geraeteartverwaltung")</li>
            <li>@Html.ActionLink("Geräteart hinzufügen", "GeraeteartHinzufuegen", "Geraeteartverwaltung")</li>
        </ul>
    </div>
</div>


<h3>Komponente hinzufügen</h3>

<div id="content">
    <table>
        <tr><td>Bezeichnung</td><td><input id="titel" type="text" /></td></tr>
    </table>


    <br /><br /><br />
    <input id="zurücksetzen" type="reset" value="Zurücksetzen" class="btn btn-primary" />
    <input id="erstellen" type="submit" value="Erstellen" class="btn btn-primary" />
    <br /><br />
    <input id="zurueck" type="submit" value="Zurück" class="btn btn-primary" />
</div>

Bravo/Bravo/Views/Geraetkomponentenverwaltung/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Geräte", "Index", "Geraeteverwaltung")</li>
            <li>@Html.ActionLink("Gerät hinzufügen", "GeraetHinzufuegen", "Geraeteverwaltung")</li>
            <li>@Html.ActionLink("Übersicht Komponenten", "Index", "Geraetkomponentenverwaltung")</li>
            <li>@Html.ActionLink("Komponente hinzufügen", "GeraetkomponenteHinzufuegen", "Geraetkomponentenverwaltung")</li>
            <li>@Html.ActionLink("Übersicht Gerätearten", "Index", "Geraeteartverwaltung")</li>
            <li>@Html.ActionLink("Geräteart hinzufügen", "GeraeteartHinzufuegen", "Geraeteartverwaltung")</li>
        </ul>
    </div>
</div>


<h3>Übersicht Komponenten</h3>