Bravo/Bravo/Controllers/BenutzerverwaltungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bravo.Controllers
{
    public class BenutzerverwaltungController : Controller
    {
        // GET: Benutzerverwaltung
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BenutzerDetails()
        {
            return View();
        }

        public ActionResult BenutzerHinzufuegen()
        {
            return View();
        }
    }
}

Bravo/Bravo/Views/Benutzerverwaltung/BenutzerDetails.cshtml
@{
        ViewBag.Title = "BenutzerDetails";
        Layout = "~/Views/Shared/_Layout.cshtml";

        string anrede, titel, name, geburtsdatum, benutzername, email, rechtegruppe, erstelldatum;


        anrede = "Herr";
        titel = "";
        name = "Max Mustermann";
        geburtsdatum = DateTime.Today.ToShortDateString();
        benutzername = "mmustermann";
        email = "max.mustermann@mustermail.com";
        rechtegruppe = "Admin";
        erstelldatum = DateTime.Today.ToShortDateString();


}

<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Benutzer", "Index", "Benutzerverwaltung")</li>
            <li>@Html.ActionLink("Benutzer hinzufügen", "BenutzerHinzufuegen", "Benutzerverwaltung")</li>
        </ul>
    </div>
</div>


<h3>Benutzer bearbeiten</h3>



<table style="width:100%;">
    <tr><td>Anrede</td><td><input id="anrede" type="text" value="@anrede" /></td></tr>
    <tr><td>Titel</td><td><input id="titel" type="text" value="" /></td></tr>
    <tr><td>Name</td><td><input id="name" type="text" value="@name" /></td></tr>
    <tr><td>Geburtsdatum</td><td><input id="geburtsdatum" type="text" value="@geburtsdatum" /></td></tr>
    <tr><td>Benutzername</td><td><input id="benutzername" type="text" value="@benutzername" /></td></tr>
    <tr><td>E-Mail</td><td><input id="email" type="text" value="@email" /></td></tr>
    <tr><td>Rechtegruppe</td><td><input id="rechtegruppe" type="text" value="@rechtegruppe" /></td></tr>
    <tr><td>Erstellt am</td><td><input id="erstelldatum" type="text" value="@erstelldatum" /></td></tr>
</table>

<br />

<input id="aendern" type="submit" value="Ändern" onclick="btnAendern_Click" class="btn btn-primary"/>
<input id="loeschen" type="submit" value="Löschen" onclick="btnLoeschen_Click" class="btn btn-primary"/>
<input id="zurueck" type="submit" value="Zurück" onclick="btnZurueck_Click" class="btn btn-primary"/>

Bravo/Bravo/Views/Benutzerverwaltung/BenutzerHinzufuegen.cshtml
@{
    ViewBag.Title = "BenutzerHinzufügen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Benutzer", "Index", "Benutzerverwaltung")</li>
            <li>@Html.ActionLink("Benutzer hinzufügen", "BenutzerHinzufuegen", "Benutzerverwaltung")</li>
        </ul>
    </div>
</div>

<h3>Benutzer hinzufügen</h3>



<div id="content">
    <table>
        <tr><td>Anrede</td><td><select id="dropdown">
                                    <option value="herr">Herr</option>
                                    <option value="frau">Frau</option>
                               </select></td></tr>
        <tr><td>Titel</td><td><input id="titel" type="text" /></td></tr>
        <tr><td>Name</td><td><input id="name" type="text" /></td></tr>
        <tr><td>Geburtsdatum</td><td><input ID="datum" type="date" /></td></tr>
        <tr><td>Adresse</td><td><input id="adresse" type="text" /></td></tr>
        <tr><td>E-Mail</td><td><input id="email" type="text" /></td></tr>
        <tr><td>Benutzername</td><td><input id="benutzername" type="text" /></td></tr>
    </table>


    <br /><br /><br />
    <input id="zurücksetzen" type="reset" value="Zurücksetzen" class="btn btn-primary" />
    <input id="erstellen" type="submit" value="Erstellen" class="btn btn-primary"/>
    <br /><br />
    <input id="zurueck" type="submit" value="Zurück" class="btn btn-primary" />
</div>

Bravo/Bravo/Views/Benutzerverwaltung/BenutzerHinzufügen.cshtml
@{
    ViewBag.Title = "BenutzerHinzufügen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Benutzerverwaltung</h2>
<h3>Benutzer hinzufügen</h3>

<div>
    <p><a href="~/Views/Benutzerverwaltung/BenutzerDetails.cshtml">Benutzer-Liste</a></p>
    <p><a href="~/Views/Benutzerverwaltung/BenutzerHinzufügen.cshtml">Benutzer hinzufügen</a></p>
</div>

<div id="adduser">
    <p>Anrede</p>
    <select id="dropdown">
        <option value="herr">Herr</option>
        <option value="frau">Frau</option>
    </select>
    <p>Titel</p>
    <input id="titel" type="text" />
    <p>Name</p>
    <input id="name" type="text" />
    <p>Geburtsdatum</p>


    <p>Adresse</p>
    <input id="adresse" type="text" />

    <p>E-Mail</p>
    <input id="email" type="text" />

    <p>Benutzername</p>
    <input id="benutzername" type="text" />

    <br /><br /><br />
    <input id="zurücksetzen" type="reset" value="Zurücksetzen" />

    <input id="erstellen" type="submit" value="Erstellen" />
</div>

Bravo/Bravo/Views/Benutzerverwaltung/Index.cshtml
@{
    ViewBag.Title = "Benutzerverwaltung";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Benutzer", "Index", "Benutzerverwaltung")</li>
            <li>@Html.ActionLink("Benutzer hinzufügen", "BenutzerHinzufuegen", "Benutzerverwaltung")</li>
        </ul>
    </div>
</div>

<h3>Übersicht Benutzer</h3>