Bravo/Bravo/Controllers/RaumverwaltungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bravo.Controllers
{
    public class RaumverwaltungController : Controller
    {
        // GET: Raumverwltung
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RaumHinzufuegen()
        {
            return View();
        }

        public ActionResult RaumDetails()
        {
            return View();
        }
    }
}

Bravo/Bravo/Views/Raumverwaltung/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Räume", "Index", "Raumverwaltung")</li>
            <li>@Html.ActionLink("Raum hinzufügen", "RaumHinzufuegen", "Raumverwaltung")</li>
        </ul>
    </div>
</div>


<h3>Übersicht Räume</h3>

Bravo/Bravo/Views/Raumverwaltung/RaumDetails.cshtml
@{
    ViewBag.Title = "RaumDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Räume", "Index", "Raumverwaltung")</li>
            <li>@Html.ActionLink("Raum hinzufügen", "RaumHinzufuegen", "Raumverwaltung")</li>
        </ul>
    </div>
</div>


<h3>Raum bearbeiten</h3>

Bravo/Bravo/Views/Raumverwaltung/RaumHinzufuegen.cshtml
@{
    ViewBag.Title = "RaumHinzufuegen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Übersicht Räume", "Index", "Raumverwaltung")</li>
            <li>@Html.ActionLink("Raum hinzufügen", "RaumHinzufuegen", "Raumverwaltung")</li>
        </ul>
    </div>
</div>


<h3>Raum hinzufügen</h3>

<div id="content">
    <table>
        <tr><td>Bezeichnung</td><td><input id="bezeichnung" type="text" /></td></tr>
        <tr><td>Notiz</td><td><input id="notiz" type="text" /></td></tr>
    </table>


    <br /><br /><br />
    <input id="zurücksetzen" type="reset" value="Zurücksetzen" class="btn btn-primary" />
    <input id="erstellen" type="submit" value="Erstellen" class="btn btn-primary" />
    <br /><br />
    <input id="zurueck" type="submit" value="Zurück" class="btn btn-primary" />
</div>