Bravo_core/Bravo/Controllers/RoomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using Bravo.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bravo.Models.ViewModels.Room;
using Bravo.Models.DatabaseEntities;
using AutoMapper;
using Bravo.Models.DatabaseEntities.Relation;

namespace Bravo.Controllers
{
    [Authorize(Roles = "Administrator,Verwaltung")]
    public class RoomController : Controller
    {
        private readonly IToolService _toolService;
        private readonly IRoomService _roomService;
        private readonly ILogger _logger;

        public RoomController(IRoomService roomService, IToolService toolService, ILoggerFactory loggerFactory)
        {
            _toolService = toolService;
            _roomService = roomService;
            _logger = loggerFactory.CreateLogger<RoomController>();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new RoomIndexViewModel() { RoomList = _roomService.Get().ToList() });
        }

        [HttpGet]
        public IActionResult Edit(long id)
        {
            if(id == 0)
            {
                return View(new RoomEditViewModel());
            }

            IRoom room = _roomService.Get(id);
            return View(new RoomEditViewModel() { Id = room.Id, Name = room.Name, ToolListFromRoom = room.Tools.Cast<Tool>().ToList(), AllTools = _toolService.Get().Cast<Tool>().ToList() });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(RoomEditViewModel viewModel)
        {
            if (viewModel.Id > 0)
            {
                IRoom roomFromDatabase = _roomService.Get(viewModel.Id);
                Mapper.Map(viewModel, roomFromDatabase);
            }
            else
            {
                _roomService.Add(Mapper.Map<Room>(viewModel));
            }

            await _roomService.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Bravo_core/Bravo/Controllers/SoftwareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using Bravo.Services;
using Bravo.Models.ViewModels.Software;
using Bravo.Models.DatabaseEntities;
using AutoMapper;

namespace Bravo.Controllers
{
    [Authorize]
    public class SoftwareController : Controller
    {
        private readonly ISoftwareService _softwareService;
        private readonly ILogger _logger;

        public SoftwareController(ISoftwareService softwareService, ILoggerFactory loggerFactory)
        {
            _softwareService = softwareService;
            _logger = loggerFactory.CreateLogger<SoftwareController>();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new SoftwareIndexViewModel() { SoftwareList = _softwareService.Get().ToList() });
        }

        [HttpGet]
        public IActionResult Edit(long id)
        {
            if (id == 0)
            {
                return View(new SoftwareEditViewModel());
            }

            ISoftware software = _softwareService.Get(id);
            return View(new SoftwareEditViewModel() { Id = software.Id, Bezeichnung = software.Bezeichnung });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SoftwareEditViewModel viewModel)
        {
            if (viewModel.Id > 0)
            {
                ISoftware softwareFromDatabase = _softwareService.Get(viewModel.Id);
                Mapper.Map(viewModel, softwareFromDatabase);
            }
            else
            {
                _softwareService.Add(Mapper.Map<Software>(viewModel));
            }

            await _softwareService.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Bravo_core/Bravo/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Bravo.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Bravo_core/Bravo/Controllers/ToolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Logging;
using Bravo.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bravo.Models.DatabaseEntities;
using AutoMapper;
using Bravo.Models.ViewModels.Tool;

namespace Bravo.Controllers
{
    [Authorize]
    public class ToolController : Controller
    {
        private readonly IToolService _toolService;
        private readonly ILogger _logger;

        public ToolController(IToolService toolService, ILoggerFactory loggerFactory)
        {
            _toolService = toolService;
            _logger = loggerFactory.CreateLogger<ToolController>();
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new ToolIndexViewModel() { ToolList = _toolService.Get().ToList() });
        }

        [HttpGet]
        public IActionResult Edit(long id)
        {
            if(id == 0)
            {
                return View(new ToolEditViewModel());
            }

            ITool tool = _toolService.Get(id);
            return View(new ToolEditViewModel() { Id = tool.Id, Name = tool.Name });
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ToolEditViewModel viewModel)
        {
            if (viewModel.Id > 0)
            {
                ITool toolFromDatabase = _toolService.Get(viewModel.Id);
                Mapper.Map(viewModel, toolFromDatabase);
            }
            else
            {
                _toolService.Add(Mapper.Map<Tool>(viewModel));
            }

            await _toolService.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

Bravo_core/Bravo/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zimmerverwaltung</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Zimmerverwaltung</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">                    
                    <li><a asp-area="" asp-controller="Tool" asp-action="Index">Geräte</a></li>
                    <li><a asp-area="" asp-controller="Room" asp-action="Index">Räume</a></li>
                    <li><a asp-area="" asp-controller="Software" asp-action="Index">Software</a></li>
                    <li><a asp-area="" asp-controller="Lieferant" asp-action="Index">Lieferant</a></li>
                    <li><a asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a></li>
                    
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="navbar_side navbar-inverse navbar-fixed-side">
        <div class="navbar_side_child navbar-inverse navbar-fixed-side-child">
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Zimmerverwaltung</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>